name: Auto-Approve Safe PRs

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    environment: themoeway-bot
    permissions:
      pull-requests: write
    if: github.actor == 'djahandarie'
    steps:
      - uses: hmarr/auto-approve-action@44888193675f29a83e04faf4002fa8c0b537b1e4 # v3.2.1
        with:
          github-token: ${{ secrets.THEMOEWAY_BOT_PAT }}
